## Please see README.md for instructions on how to configure this file.
## https://github.com/Chalwk/HaloDiscordBot/blob/main/README.md

HALO_SERVERS:
  - name: "DEV SERVER"
    port: 47652
    bind_address: "0.0.0.0"
    secret_key: "your-very-secret-key"
    allowed_ips:
      - "192.168.1.100"
      - "203.0.113.0/24"
    channels:
      general: "1504095256184881163"
      admin: "1504095321918275765"

COMMAND_PERMISSIONS:
  game_status: "ADMINISTRATOR"
  halo: "ADMINISTRATOR"

GAME_EVENTS:

  show_server_name: true

  embeds:

    event_chat:
      enabled: true
      channel: "general"
      title: " "
      color: "WHITE"
      description: "**💬 Chat** → `{name}`: *{msg}*"

    event_command:
      enabled: true
      channel: "admin"
      title: " "
      color: "MAGENTA"
      description: "**⌘ Command** → `{name}`: `{cmd}`"

    event_death:
      enabled: true
      channel: "general"
      title: " "
      color: "RED"
      type:
        1: "**☠️ Death:** `{killer_name}` drew first blood on `{victim_name}`"
        2: "**☠️ Death:** `{victim_name}` was killed from the grave by `{killer_name}`"
        3: "**☠️ Death:** `{victim_name}` was run over by `{killer_name}`"
        4: "**☠️ Death:** `{victim_name}` was killed by `{killer_name}`"
        5: "**☠️ Death:** `{victim_name}` committed suicide"
        6: "**☠️ Death:** `{victim_name}` was betrayed by `{killer_name}`"
        7: "**☠️ Death:** `{victim_name}` was squashed by a vehicle"
        8: "**☠️ Death:** `{victim_name}` fell to their death"
        9: "**☠️ Death:** `{victim_name}` was killed by the server"
        10: "**☠️ Death:** `{victim_name}` died"

    event_end:
      enabled: true
      channel: "general"
      title: " "
      color: "RED"
      description: "**🏁 Game Ended** → `{map}` **-** `{gt} (FFA: {ffa})`"

    event_join:
      enabled: true
      channel: "general"
      title: " "
      color: "CYAN"
      description: "**🟢 Join** → `{name}` **-** `{total}/16`"

    event_leave:
      enabled: true
      channel: "general"
      title: " "
      color: "ORANGE"
      description: "**🔴 Quit** → `{name}` **-** `{total}/16`"

    event_login:
      enabled: true
      channel: "admin"
      title: " "
      color: "PINK"
      description: "**🔐 Login** → `{name}`\n\n**Admin Level:** `{lvl}`"

    event_map_reset:
      enabled: false
      channel: "general"
      title: " "
      color: "ORANGE"
      description: "**♻️ Map Reset** → `{map}` **-** `{gt} ({ffa})`"

    event_score:
      enabled: true
      channel: "general"
      title: " "
      color: "YELLOW"
      type:
        1: "**{name}** captured the flag for the **{team}** team!\n\n🟥 Red Score: **{red_score}**\n🟦 Blue Score: **{blue_score}**\n🏁 Scorelimit: **{scorelimit}**"
        2: "**{name}** completed a lap for **{team}** team!\n🏁 Team Total Laps: **{total_team_laps}/{scorelimit}**\n🚩 Player Laps: **{score}**"
        3: "**{name}** finished a lap.\n🏆 Total Laps Completed: **{score}/{scorelimit}**"
        4: "**{name}** scored for **{team}** team!\n\n🟥 Red Score: **{red_score}**\n🟦 Blue Score: **{blue_score}**\n🏁 Scorelimit: **{scorelimit}**"
        5: "**{name}** scored!\n\n🟥 Red Score: **{red_score}**\n🟦 Blue Score: **{blue_score}**\n🏁 Scorelimit: **{scorelimit}**"

    event_snap:
      enabled: true
      channel: "admin"
      title: " "
      color: "DARK_GRAY"
      description: "{name} snapped (bot detection)"

    event_spawn:
      enabled: false
      channel: "general"
      title: " "
      color: "GRAY"
      description: "**✨ Spawn** → `{name}` Team: `{team}`"

    event_start:
      enabled: true
      channel: "general"
      title: " "
      color: "GREEN"
      description: "**🗺️ Game Started** → `{map}` **-** `{gt} (FFA: {ffa})`"

    event_team_switch:
      enabled: false
      channel: "general"
      title: " "
      color: "BLUE"
      description: "**🔄 Team Switch** → `{name}` → `{team}`"